### ISSUE TITLE
A method for validating adjoint implementation of a linear operation

### ISSUE THREAD

**Issue by tianrluo** [mikgroup/sigpy#110]
Hey folks,

Thanks for creating this awesome tool!

I was wondering if you'd be interested in including a general method that may facilitate validation of adjoint linear operations.
Something as simple as checking if <d, Ap> == <A^H d, p> holds for a pair of primal/dual random vectors {p, d}.
I thought such feature could ease common developments, e.g., checking if the adjoint of a multi-dim spatial difference operator is correctly implemented.
(My apologize if it already exists and I've missed it.) 

I feel like the following patch can do the trick, but am not so sure if it's compatible with things like different backends, etc.

```diff
From e88c3fdf0e8dd3db5e38b722316453b0d3ea8d74 Mon Sep 17 00:00:00 2001
From: <tianrluo@users.noreply.github.com>
Date: Thu, 19 May 2022 19:56:24 -0400
Subject: [PATCH] A tool for adjoint operator validation.

---
 sigpy/linop.py | 17 +++++++++++++++++
 1 file changed, 17 insertions(+)

diff --git a/sigpy/linop.py b/sigpy/linop.py
index 0efd1af..cdfd533 100644
--- a/sigpy/linop.py
+++ b/sigpy/linop.py
@@ -109,6 +109,23 @@ class Linop():
     def _normal_linop(self):
         return self.H * self

+    def _valid_adjoint(self, rtol=1e-05, atol=1e-08, equal_nan=False) -> bool:
+        """Validate if adjoint is correctly implemented
+
+        For random primal/dual vectors, {p, d}, expect <d, Ap> == <Aᴴd, p>.
+        """
+        p1 = np.random.randn(self.ishape)+1j*np.random.randn(self.ishape)
+        d1 = self.apply(p1)
+
+        d2 = np.random.randn(self.oshape)+1j*np.random.randn(self.oshape)
+        p2 = self.H.apply(d2)
+
+        res_fwd = (d2.ravel()).conj().T @ d1.ravel()  # <  d, Ap>
+        res_adj = (p2.ravel()).conj().T @ p1.ravel()  # <Aᴴd,  p>
+
+        return np.isclose(res_fwd, res_adj,
+                          rtol=rtol, atol=atol, equal_nan=equal_nan)
+
     @property
     def H(self):
         r"""Return adjoint linear operator.
--
2.25.1
```

Thanks!

**Comment by sidward** [comment]
Hello! There are sanity checks available in the tests.
Please see this in particular: https://github.com/mikgroup/sigpy/blob/1817ff849d34d7cbbbcb503a1b310e7d8f95c242/tests/test_linop.py#L40

**Comment by tianrluo** [comment]
Ah, indeed, thanks!
