### ISSUE TITLE
BART vs sigpy, which should I choose?

### ISSUE THREAD

**Issue by Michaelsqj** [mikgroup/sigpy#118]
For anyone having experience of using both sigpy and bart, may I ask which package is more efficient in terms of speed and memory consumption? Particularly for NUFFT computation. I'm just starting to implement some memory hungry reconstruction, and wondering which package shall I choose?

**Comment by uecker** [comment]
Unclear. Traditionally BART was very bad as it used a lot of memory to make everything parallel. Recently, Moritz from my group reduced this a lot and it should be pretty optimal when used with the right options.
