### ISSUE TITLE
sigpy on conda-forge / support for newest python versions

### ISSUE THREAD

**Issue by gschramm** [mikgroup/sigpy#120]
**Is your feature request related to a problem? Please describe.**
Currently, `sigpy` is only available a private conda channel and does not support the newest python version.

**Describe the solution you'd like**
I suggest to create a recipe to build and distribute `sigpy` via `conda-forge`.
This sigpy is pure python and available via `pypi`, creating the recipe is easy (e.g. automatic via `grayskull`).
I am happy to help creating / staging the recipe for `conda-forge`.

**Comment by frankong** [comment]
Good idea, please create the recipe. thanks!

**Comment by gschramm** [comment]
great. I will stage a recipe in the upcoming days.
should I list you as maintainer?

**Comment by frankong** [comment]
sounds good

**Comment by gschramm** [comment]
I finally had time to add a staged-recipe to conda-forge (see this [PR](https://github.com/conda-forge/staged-recipes/pull/22733)).

1. Can you add a comment to the PR to confirm that you are also a maintainer? (the maintance work is minimal thanks to all the excellent bots on conda-forge).
2. compared to your recipe, I added a all tests in `tests/*.py` and `tests/mri/*.py`

**Comment by sidward** [comment]
Hi @gschramm please also add me as a maintainer. Let me ping Frank to confirm that PR.

**Comment by gschramm** [comment]
> 

sure. I will adapt the conda-forge PR right now :)

**Comment by gschramm** [comment]
@sidward added you as a maintainer in the conda-forge recipe. Can you leave a comment in the PR mentioned above stating that you are willing to serve as maintainer?

**Comment by frankong** [comment]
Thanks! Ya and @sidward can also confirm
