### ISSUE TITLE
nlinv / jsense

### ISSUE THREAD

**Issue by uecker** [mikgroup/sigpy#121]
As pointed out by somebody to me at the Sedona Workshop who was confused about this: SigPy calls the regularized bilinear recon JSENSE. But the version with regularization for image and coil sensitivities is NLINV. This is a bit unfortunate,  in my opinion.

**Comment by frankong** [comment]
Hi Martin :)
nlinv is cited in the references: https://github.com/mikgroup/sigpy/blob/8d2030d98fe1d6199f430828f1d8c67c1502ad56/sigpy/mri/app.py#L234-L237
By default, regularization is turned off with lambda=0, so that's JSENSE. 

I can merge a pull request, If you have suggestions on a clearer docstring.

**Comment by uecker** [comment]
Am Montag, dem 03.04.2023 um 22:41 -0700 schrieb Frank Ong:
> Hi Martin :)
> nlinv is cited in the references: https://github.com/mikgroup/sigpy/blob/8d2030d98fe1d6199f430828f1d8c67c1502ad56/sigpy/mri/app.py#L234-L237
> By default, regularization is turned off with lambda=0, so that's JSENSE.
> I can merge a pull request, If you have suggestions on a clearer docstring.

Maybe add something like this:

"This formulation with regularization corresponds to the version
described in the NLINV paper. Without regularization (which is the
default) it corresponds to the version from the JSENSE paper but
using a truncated Fourier representation of the coils (as in NLINV)
instead of polynomials."

(assuming this is what it does)

Martin

**Comment by uecker** [comment]
Am Montag, dem 03.04.2023 um 22:41 -0700 schrieb Frank Ong:
> Hi Martin :)
> nlinv is cited in the references: https://github.com/mikgroup/sigpy/blob/8d2030d98fe1d6199f430828f1d8c67c1502ad56/sigpy/mri/app.py#L234-L237
> By default, regularization is turned off with lambda=0, so that's JSENSE.
> I can merge a pull request, If you have suggestions on a clearer docstring.

Maybe add something like this:

"This formulation with regularization corresponds to the version
described in the NLINV paper. Without regularization (which is the
default) this corresponds to the version from the JSENSE paper but using a
truncated Fourier representation of the coils (as in NLINV) instead
of polynomials."

(assuming this is what it does)

Martin

**Comment by frankong** [comment]
Addressed in https://github.com/mikgroup/sigpy/pull/122

**Comment by uecker** [comment]
Thanks Frank!
