### ISSUE TITLE
Install sigpy under Ubuntu 22.04 (np.float and co)

### ISSUE THREAD

**Issue by m-a-x-i-m-z** [mikgroup/sigpy#129]
I'm trying to install sigpy under the current Ubuntu LTS version using pip but seem to be stuck: 

1: the current version in the pip repository (0.1.25) seems to still suffer from the np.float problem 
2: trying to downgrade numpy fails seemingly due to the compiler incompatibility 
3: trying to run pip directly from git produces an error (see below). Probably something is not right in pyproject.toml ...

**To Reproduce**

1: pip install sigpy 
most functions would then fail due to the no.float problem.

2: does not concern this project so much so I leave it out

3: pip install 'sigpy@git+https://github.com/mikgroup/sigpy.git'

Defaulting to user installation because normal site-packages is not writeable
Collecting sigpy@ git+https://github.com/mikgroup/sigpy.git
  Cloning https://github.com/mikgroup/sigpy.git to /tmp/pip-install-rmnh3q29/sigpy_833b9060ff8943a18a2141e75febf85a
  Running command git clone --filter=blob:none --quiet https://github.com/mikgroup/sigpy.git /tmp/pip-install-rmnh3q29/sigpy_833b9060ff8943a18a2141e75febf85a
  Resolved https://github.com/mikgroup/sigpy.git to commit 63933394d6e9a334d58db27bbf48207421431d12
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for sigpy@ git+https://github.com/mikgroup/sigpy.git from git+https://github.com/mikgroup/sigpy.git.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package sigpy produced metadata for project name unknown. Fix your #egg=sigpy fragments.
Discarding git+https://github.com/mikgroup/sigpy.git: Requested unknown from git+https://github.com/mikgroup/sigpy.git has inconsistent name: filename has 'sigpy', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement sigpy (unavailable) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 0.1.25)
ERROR: No matching distribution found for sigpy (unavailable)

**Comment by schuenke** [comment]
This was reported several times (e.g. #123, #124), but the issues get closed without releasing the fix 😞 

Would be really great if you could take care of this!

**Comment by jonbmartin** [comment]
Just got added as a sigpy maintainer and resolved with version 0.1.26
