### ISSUE TITLE
module 'numpy' has no attribute issues

### ISSUE THREAD

**Issue by MantisShrimpSushi** [mikgroup/sigpy#130]
I encountered this problem when I tried to use some of the sigpy functions and kept recevieing messages like:

module 'numpy' has no attribute 'complex'
module 'numpy' has no attribute 'float'

which I believe is due to numpy version, as np.float and np.complex is marked deprcated since 1.20.1 and is now complete abandoned in newer versions.

I am currently solving this problem by "np.float = np.float64" actively because there's too many to replace in sigpy.

I hope if in a future version of sigpy this issued can be updated!

 - OS: Windows 11
 - Python: 3.9.13
 - numpy: 1.24.1
![1](https://github.com/mikgroup/sigpy/assets/76458938/9c6b0b7d-b02e-4970-9b93-051f8a77d9e6)
![2](https://github.com/mikgroup/sigpy/assets/76458938/65d372d4-4583-43e3-8883-dde1b54c3bbc)
![3](https://github.com/mikgroup/sigpy/assets/76458938/95f6b5ae-d7d1-4ee4-9639-6a1443ebe3e9)

**Comment by schuenke** [comment]
This has been reported several times (#123, #124, #129) and was fixed with PR #126 in May, but unfortunately the fix has not been released yet. 

Again, I would like to encourage the sigpy maintainers to do so.

**Comment by jonbmartin** [comment]
resolved with version 0.1.26
