### ISSUE TITLE
Sigpy incompatible with scipy 1.14.0 and numpy 2.0

### ISSUE THREAD

**Issue by schuenke** [mikgroup/sigpy#142]
Recently, scipy 1.14.0 and numpy 2.0 have been released and several function signatures have changed leading to problems with the current sigpy version. 

The most relevant changes are:

- np.infty was removed (use np.inf instead)
- scipy: "Coinciding with changes to function signatures (e.g. removal of a deprecated
keyword), we had deprecated positional use of keyword arguments for the
affected functions, which will now raise an error."
- scipy.integrate.{simps,trapz,cumtrapz} have been removed in favour of simpson, trapezoid, and cumulative_trapezoid.
- the blackman window function needs to be called from scipy.signal.windows instead of scipy.signal directly

I will create a PR, but wanted to open an Issue to ensure users find it here.

**Comment by schuenke** [comment]
Nobody feels responsible? I already created a PR (#143) for it 2 weeks ago. Shouldn't be to much work left imo.

**Comment by jweine** [comment]
Commenting to upvote and create attention. Just to mention, the `scipy.firls`  positional weight argument starts being incompatible from `1.12`.

**Comment by schuenke** [comment]
This is still an issue

**Comment by stebix** [comment]
Hi all,

this is still an issue right? I think @schuenke provided a good PR. I am currently attempting to install the very nice `sigpy` package, but version constraints together with conda lead to several install-delete-reinstall cycles with different package install orders and manually pinned versions to get everything working ...
