### ISSUE TITLE
Unable to reconstruct raw data 

### ISSUE THREAD

**Issue by soumickmj** [mikgroup/sigpy#18]
I'm trying to reconstruct data acquired by Siemens Skyra scanner with Star VIBE (Golden Angle) sequence. I'm using sigpy.mri.radial for generating the trajectories and then sigpy.linop.NUFFT for reconstructing the data. Please help.

**Comment by frankong** [comment]
Hi Soumick, I will need more information. Can you follow the issue templates and update your issue? https://github.com/mikgroup/sigpy/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
https://github.com/mikgroup/sigpy/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by frankong** [comment]
Closing the issue due to inactivity > two weeks.
