### ISSUE TITLE
Cannot do fft with 2D ksp data

### ISSUE THREAD

**Issue by ShannonZ** [mikgroup/sigpy#21]
**Describe the bug**
Throw “ValueError: axes don't match array” when doing fft with 2D ksp data.

The kspace data was acquired using a single slice SE sequence (256*192).

**To Reproduce**
I made some changes in the demo to reproduce the same error,

import numpy as np
import sigpy as sp
import sigpy.mri as mr
import sigpy.plot as pl

ksp = np.load('data/cartesian_ksp.npy')
ksp = ksp[0,:,:]
img_shape = ksp.shape

F = sp.linop.FFT(ksp.shape, axes=(0,1))
pl.ImagePlot(F.H * ksp, z=0, title=r'$F^H y$')
**Expected behavior**
FFT should support 2-N dimensional data.

**Desktop (please complete the following information):**

Nothing about OS.

**Comment by ShannonZ** [comment]
It seems that there are something wrong configured in my computer that caused the problem. I can do 2D FFT in another computer. Sorry to disturb you.

May I ask you another question?
The sampling mask used in the demo is a mask used in practice?  Why use this kind of mask? I don't think this acquiring mask could shorten the Acq. Time.
I'm a newbie in this field. Could you please give me some basic tutorials? Or is it possible to give me an email?

a858561674@gmail.com, Shann, A student majoring in BME.

**Comment by sidward** [comment]
Hi Shann,

This page should help: http://people.eecs.berkeley.edu/~mlustig/CS.html

**Comment by ShannonZ** [comment]
Thank you very much

**Comment by ShannonZ** [comment]
I cannot understand why the sampling pattern could shorten the sampling time.
Taking SE (2D, single slice imaging) as an example:
Each row of mask has at least one non-zero value so the total number of Phase Encoding steps did not decrease.
The Total Samling time = #PhaseEncoding * TR *Averages. If #PhaseEncoding not change, the total time should also not be reduced.
