### ISSUE TITLE
What's wrong with my reconstruction procedure?

### ISSUE THREAD

**Issue by ShannonZ** [mikgroup/sigpy#23]
Code First: https://github.com/ShannonZ/playground

**Why is the reconstructed image so obscure**
ksp = np.load('ksp.npy')
img_shape = ksp.shape

F = sp.linop.FFT(ksp.shape, axes=(0,1))
mask = abs(ksp)>0
P = sp.linop.Multiply(ksp.shape, mask)
W = sp.linop.Wavelet(img_shape)
wav = W  * F.H * ksp

A = P * F * W.H

lamda = 0.005
proxg = sp.prox.L1Reg(wav.shape, lamda)
alpha = 1
wav_thresh = proxg(alpha, wav)

max_iter = 100
alpha = 1

def gradf(x):
    return A.H * (A * x - ksp)

wav_hat = np.zeros(wav.shape, np.complex)
alg = sp.alg.GradientMethod(gradf, wav_hat, alpha, proxg=proxg, max_iter=max_iter)

while not alg.done():
    alg.update()
    print('\rL1WaveletRecon, Iteration={}'.format(alg.iter), end='')

pl.ImagePlot(W.H(wav_hat))
**Any demo about recon from normal single coil sampled data**
I can only find tutorials about reconstruction from multi-coil data.

**Comment by frankong** [comment]
You should increase regularization parameter `lamda`, which should be proportional to your image magnitude. If you look at `F.H * ksp`, you see that the maximum amplitude is roughly ~2000, so your `lamda` should also be scaled to ~0.005 * 2000.

That'll reduce the incoherent artifacts from left to right:
![Screen Shot 2019-07-10 at 10 24 00 PM](https://user-images.githubusercontent.com/9143405/61024114-6c8f5a00-a361-11e9-82d5-23e94a325576.png)

There are still some significant ghosting artifacts from left to right, which do not seem like random under sampling artifact. Might be other sources of errors.

**Comment by ShannonZ** [comment]
Thank you!
