### ISSUE TITLE
NUFFT is producing unexpected result

### ISSUE THREAD

**Issue by soumickmj** [mikgroup/sigpy#39]
When nufft is applied to a real image, and then adjoint nufft to bring back to image space, the returned image should have imaginary values close to zero. But when I'm trying to do the same with nufft and adjoint nufft of sigpy, the imaginary part isn't really close to zero. 
When I tried to do the same thing, including same angles, with PyNufft, it gave me desired results.
I'm wondering why such thing is happening?

One more thing, when oversampling is not desired, I'm passing oversamp as 1, it returns nan values (happens during the calculation of apodization). 

Thanks for your help in advance :)

**Comment by kmjohnson3** [comment]
Are your coordinates symmetric? See simple code below which does not reproduce your results. The oversampling bug returning NaNs appear to be limited to the GPU and also present with oversampling factors of 2.0.

```python
import numpy as np
import sigpy as sp
import sigpy.mri as mri

image = sp.shepp_logan( (256,256))
coord = sp.mri.radial( (300,300,2), img_shape=image.shape, golden=False)
#coord += 1.0
#coord = np.concatenate([coord, -coord],axis=0) # Force Symetric k-space

# CPU
kspace = sp.fourier.nufft(image, coord, oversamp=2, width=4)
image2 = sp.fourier.nufft_adjoint(kspace,coord, oversamp=2, width=4)

#GPU
image_gpu = sp.to_device(image, sp.Device(0))
coord_gpu = sp.to_device(coord, sp.Device(0))
kspace_gpu = sp.fourier.nufft(image_gpu, coord_gpu, oversamp=2.5, width=4)
image2_gpu = sp.fourier.nufft_adjoint(kspace_gpu,coord_gpu, oversamp=2.5, width=4)
image2_gpu = sp.to_device(image2_gpu,sp.cpu_device)   

print(f'GPU:Imag Signal {np.sum(np.abs(np.imag(image2_gpu)))/np.sum(np.abs(image2_gpu))}')
print(f'CPU:Imag Signal {np.sum(np.abs(np.imag(image2)))/np.sum(np.abs(image2))}')

import matplotlib.pyplot as plt
plt.figure()
plt.subplot(221)
plt.imshow(np.imag(image2))
plt.subplot(222)
plt.imshow(np.real(image2))

plt.subplot(223)
plt.imshow(np.imag(image2_gpu))
plt.subplot(224)
plt.imshow(np.real(image2_gpu))
plt.draw()
plt.show()
```

**Comment by soumickmj** [comment]
Thanks. I'm using the coordinates from sigpy itself (sp.mri.radial) and using golden angle sampling (golden=True). For both forward nufft and adjoint, I'm using oversamp as 2 and width as 4. And I'm running on CPU. I have not tested with GPU yet.

**Comment by kmjohnson3** [comment]
Golden angle sampling is not symmetric so you will have some imaginary signal.

**Comment by frankong** [comment]
@soumickmj if you can share a code snippet to reproduce this, that'll greatly help addressing this.
