### ISSUE TITLE
What is the expected shape for a 3D radial kspace?

### ISSUE THREAD

**Issue by mscipio** [mikgroup/sigpy#46]
Hello,
I am trying to setup a script to reconstruct a dataset acquired with a radialVIBE sequence. The coordinate sampling scheme is basically a radial sampling in the axial plane x-y, and a full cartesian sampling in the z direction.

I built my own function for this purpose, but the only way I am able to perfome the 3D reconstruction, is if I loop each slice at a time, along the z direction. If I pass the all kspace to the function sp.nufft_adjoint, I get all sorts of errors.

I have been thinking that maybe the problem is in the shape of the kspace.
So far I am trying to pass it as: `[n_coils, n_slices, n_spokes, n_ro]`

Let me know if you need more information.
Thanks

**Comment by kmjohnson3** [comment]
For stacked 3D radial k-space you can stack the operators you need to make a suitable encoding operator. Below is a code snippet from code to create a 4D matrix (slice + time) from a stack of 2D operators. We are working to modify some of the apps to take an encoding operator rather than data to make them more flexible and will do a pull request once cleaned up. 

`ES = sp.linop.Diag([sp.mri.linop.Sense(mps[:,slice,:,:],
                                           coord = coords[frame,slice,:,:],
                                           weights = None,
                                           coil_batch_size = None) for slice in range(Nslices) for frame in range(Nt)])

Rs1 = sp.linop.Reshape(oshape=ES.ishape, ishape=(Nt,Nslices,Ny,Nx))
Rs2 = sp.linop.Reshape(oshape=(Nt,Nslices,Ncoils,Npts), ishape=ES.oshape)

SENSE = Rs2*ES*Rs1`

**Comment by mscipio** [comment]
Are you sure that the way you input the coordinates array will work? Don't you need to have `nDim` as last dimension of the coords array?

**Comment by kmjohnson3** [comment]
In this example the coordinates will be Npts x 2. This was pulled from a working spiral recon and the Npts is actually the number of readouts* number of arms (flattened).

**Comment by mscipio** [comment]
I came up with this so far and I am decently satisfied as it seems able to handle anything from 2D to 4D:
```python
def radialVibe(ksp, dcf, coord, oshape=None, oversamp=1.25,width=4):
    ndim = len(oshape)-1

    if ndim == 2:
        output = sp.nufft_adjoint(ksp * dcf, coord, oshape, oversamp,width)

    elif ndim == 3:
        [nz,nc,ny,nx] = oshape
        F = sp.linop.Diag([sp.linop.NUFFT([nc,ny,nx], 
                                          coord, 
                                          oversamp, 
                                          width) for sl in range(nz)])
        Rs1 = sp.linop.Reshape(oshape=F.ishape, ishape=oshape)
        Rs2 = sp.linop.Reshape(oshape=ksp.shape, ishape=F.oshape)
        FT = Rs2*F*Rs1
        output = FT.H * (ksp * dcf)

    elif ndim == 4:
        [nt,nz,nc,ny,nx] = oshape
        F = sp.linop.Diag([sp.linop.NUFFT([nc,ny,nx], 
                                          coord, 
                                          oversamp, 
                                          width) for sl in range(nz) for tt in range(nt)])
        Rs1 = sp.linop.Reshape(oshape=F.ishape, ishape=oshape)
        Rs2 = sp.linop.Reshape(oshape=ksp.shape, ishape=F.oshape)
        FT = Rs2*F*Rs1
        output = FT.H * (ksp * dcf)
    
    else:
        raise('Something wrong with oshape ...')
        return
    return output
````

The limit is that building the multi-slice/multi-frame operator as a stack of foor loops makes the execution time scale almost linearly with the size of the problem. At the moment, it taks 2.5 minutes on my pc to invert a 3D kspace with size `(47, 6, 2380, 512)` .
I will keep an eye around to see if you come up with some clever solution.

I was trying to test the same function on GPU, but it seems that mine is too small to fit the data I am working with. Is there any chance that you have some option to transfer the data `by batch` to the device?

Thanks for the help!

**Comment by kmjohnson3** [comment]
There is a ToDevice linop that you could use to move things to the GPU for execution if you are low on memory. Certainly it can be challenging to shuffle data around if you are GPU memory limited.

**Comment by mscipio** [comment]
Yes, I saw that, but I haven't had success in using it so far.
Ideally, what I am trying to do is wrapping the `sp.linop.NUFFT` linop (from the code above, in the switch condition for `elif ndim == 4`) using the `sp.linop.ToDevice`:

```python
N = sp.linop.NUFFT([nc,ny,nx], 
                    coord, 
                    oversamp, 
                    width)
D = sp.linop.ToDevice([nc,ny,nx], 
                      odevice = 0, #GPU
                      idevice = -1) #CPU
F = sp.linop.Diag([ N*D for sl in range(nz) for tt in range(nt)])
```

**Comment by mscipio** [comment]
Ok, I found a solution that seems to work! :)
I will leave it here so that  aybe it can help someone else:
``` python
        device = 0
        [nt,nz,nc,ny,nx] = oshape
        Dr = sp.linop.ToDevice([nc,ny,nx], 
                      odevice = device, #GPU
                      idevice = -1) #CPU
        Dl = sp.linop.ToDevice(ksp.shape[-3:], 
                      odevice = -1, #CPU
                      idevice = device) #GPU
        F = sp.linop.Diag([Dl*sp.linop.NUFFT([nc,nx,nx], 
                                           sp.to_device(np.squeeze(coord[tt,:,:,:]),device), 
                                           oversamp, 
                                           width)*Dr for tt in range(nt) for sl in range(nz) ])
        Rs1 = sp.linop.Reshape(oshape=F.ishape, ishape=oshape)
        Rs2 = sp.linop.Reshape(oshape=ksp.shape, ishape=F.oshape)
        FT = Rs2*F*Rs1
        output = FT.H * (ksp * dcf[:,np.newaxis,np.newaxis,:,:]).astype(np.complex64)
```

**Comment by sidward** [comment]
Please close the issue if it has been resolved!
