### ISSUE TITLE
[Iterative reconstruction with L2 norm regularization] What is the right way to pass a "reference" image as a prior?

### ISSUE THREAD

**Issue by mscipio** [mikgroup/sigpy#48]
Hi again,
sorry for the "improper" use of Github Issues, but I don't see other ways of getting in touch with you.
I began experimenting with the use of the `sp.app.LinearLeastSquares` class to build iterative reconstruction algorithms.

What I'd like to do is to perform a regularized reconstruction, while using a 'target' image (let's say a fully sampled anatomy) as prior information.
At the moment, after building a forward operator A which seems to work for my problem, I am doing the following:

```python
super().__init__(A, y, max_iter = max_iter, show_pbar=show_pbar, 
                 z = reference, solver = 'ConjugateGradient', **kwargs)
```

But the results are not as expected. Am I interpreting the meaning of the `z` variable in the wrong way, or should I look somewhere else to solve the problem?

Thanks

**Comment by mscipio** [comment]
Some additional details about what I mean by "results are not as expected".
This is a snippet of the code I am using while trying to debug the 'app' I am trying to build.
Ideally, my dataset is 4D, with shape [nt,nz,ny,nz] for the image and [nt,nz,nc,ntr,nro] for the kspace. This code is supposed to process only one time frame (indexed by `tt`)

```python
A = Sense3D(im_mps, 
                     coord[tt,:,:,:], 
                     ishape=oshape[1:], 
                     oshape=ishape[1:], 
                     coil_batch_size = coil_batch_size, 
                     device=device)
y = (ksp[tt,:,:,:,:] * dcf[tt,np.newaxis,np.newaxis,:,:]).astype(np.complex64)
solver = sp.app.LinearLeastSquares(A, y, max_iter = 20, lamda=0, show_pbar=True, 
                                           z = reference[tt,:,:,:], solver = 'ConjugateGradient')
output[tt,:,:,:] = solver.run() 
        status_check(tt, nt, tstart=tstart)
```
Where `Sense3D `is a function defined as:
```python
def Sense3D(mps, coord, ishape, oshape, coil_batch_size = None, device=-1):
    [nz,ny,nx] = ishape
    Dr = sp.linop.ToDevice(ishape[1:], 
                          odevice = device, #GPU
                          idevice = -1) #CPU
    Dl = sp.linop.ToDevice(oshape[1:], 
                  odevice = -1, #CPU
                  idevice = device) #GPU
    F = sp.linop.Diag([Dl*sp.mri.linop.Sense(sp.to_device(np.squeeze(mps[sl,:,:,:]),device),
                                             coord = sp.to_device(np.squeeze(coord),device), 
                                             ishape = [ny,nx],
                                             weights = None,
                                             coil_batch_size = coil_batch_size)*Dr for sl in range(nz) ])
    Rs1 = sp.linop.Reshape(oshape=F.ishape, ishape=ishape)
    Rs2 = sp.linop.Reshape(oshape=oshape, ishape=F.oshape)
    FT = Rs2*F*Rs1
    return FT
```
As you can see, I set `lamda=0`, and I was expecting a result close to doing `output[tt,:,:,:] = A.H*y`

Instead, this is what I get from the code above:
![image](https://user-images.githubusercontent.com/17526160/80388806-544ce500-8878-11ea-8429-e682c14f0283.png)


While doing `A.H*y` gives me this:
![image](https://user-images.githubusercontent.com/17526160/80388831-5b73f300-8878-11ea-8e13-d54d1297b75c.png)

Could it be an issue with how I defined the `A` operator?

**Comment by frankong** [comment]
Hi--
I see a potential issue is that you are premultiplying `y` with `dcf`, but instead this should be used incorporated in `A` as well. Instead you probably want to do multiply `y` with `dcf**0.5` and `A` with `sigpy.linop.Multiply(y.shape, dcf**0.5)` as well.

You can also directly use the [SenseRecon App](https://sigpy.readthedocs.io/en/latest/generated/sigpy.mri.app.SenseRecon.html#sigpy.mri.app.SenseRecon). It uses the LinearLeastSquares App and supports `z` and other arguments. You can use the `weights` argument to supply `dcf`.
