### ISSUE TITLE
KeyError: 'S' in _xpay_cuda

### ISSUE THREAD

**Issue by wgrissom** [mikgroup/sigpy#50]
When running the L1WaveletRecon app on my GPU, python is throwing this error, as though it doesn’t understand what the ’S’ in ’S a’ stands for, on line 482 of util.py. My knowledge of cupy is limited but reading the code, it looks like _xpay_cuda defines a CUDA kernel that calculates x + a*y, where a is a scalar (which is what ’S’ signifies) and x and y are tensors (’T’).

To reproduce:
Invoke L1WaveletRecon on the GPU

Error text:
Traceback (most recent call last):
 File "./prom_nufft_test_3d.py", line 69, in <module>
   show_pbar=False, device=sp.Device(0)).run()
 File "/nas/home/grissowa/sigpy-rf/sigpy/app.py", line 85, in run
   self.alg.update()
 File "/nas/home/grissowa/sigpy-rf/sigpy/alg.py", line 63, in update
   self._update()
 File "/nas/home/grissowa/sigpy-rf/sigpy/alg.py", line 187, in _update
   util.axpy(self.x, -self.alpha, self.gradf(self.x))
 File "/nas/home/grissowa/sigpy-rf/sigpy/util.py", line 441, in axpy
   _axpy_cuda(a, x, y)
 File "cupy/core/_kernel.pyx", line 540, in cupy.core._kernel.ElementwiseKernel.__call__
 File "cupy/core/_kernel.pyx", line 587, in cupy.core._kernel.ElementwiseKernel._decide_params_type
 File "cupy/core/_kernel.pyx", line 299, in cupy.core._kernel._decide_params_type_core
KeyError: ’S'

My nvcc —version output: 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

I am running this in a Conda environment with python 3.6, with CUDA 10.1.

**Comment by sidward** [comment]
Hi! I came across the same issue too. Take a look at Pull Request #42 for a quick fix that I have been using.

**Comment by wgrissom** [comment]
Thank you for the response! So is the quick fix to just change S to T?

**Comment by sidward** [comment]
I am not sure. Pinging @frankong

**Comment by frankong** [comment]
Sorry for the delayed response. The latest master branch should fix this now. Let me know if that doesn't work.

**Comment by frankong** [comment]
Closing issue as it seems to be resolved.

**Comment by cth7** [comment]
Hi @frankong , I did a quick test on the GPU and it looks like the new axpy uses more memory than the previous CuPy ElementwiseKernel.

New axpy:
```python
y += a * x
```
The way I understand it, an array is created for `a * x`. Then that array is added to y in-place. That array is deallocated after but it still increases total memory required. Whereas the ElementwiseKernel wouldn't create an intermediate array.

Not sure what's the best fix for this... It would be useful to reduce total memory required but it seems like there are other issues arising from datatypes.
