### ISSUE TITLE
sigpy.gridding kernel input

### ISSUE THREAD

**Issue by emilljungberg** [mikgroup/sigpy#53]
I'm trying to use the `sigpy.gridding` method but having some issues with this, mainly with regard to specifying the kernel. I'm trying to do spline interpolation but when I specify `kernel='spline'` I get an error which I understand after looking in the source code where the kernel is specified as an array. Can you provide some guidance for how to use this function by specifying the kernel as an array? In particular, I'd be interested to know if it would be possible to do nearest neighbour gridding.

Thanks!

**Comment by frankong** [comment]
Sorry for the late reply. The old version of interpolation uses an array to specify the kernel.
But the new version (071a82d7b02a3e5e1d2cb5e2675e6960caa08b83) uses a string and internally exactly calculates the kernel.

Calling interpolation/gridding with kernel="spline" and param=0 should correspond to nearest neighbor.
