### ISSUE TITLE
add __version__ to sigpy

### ISSUE THREAD

**Issue by hcmh** [mikgroup/sigpy#59]
Hi Frank,

I recently wanted to try out sigpy and had a version installed, but didn't know which one. Finding that out was surprisingly difficult, as sigpy does not have a sigpy.__version__ member. Instead, I actually started comparing the source code that I found in my python path.

Of course, with pip (and probably conda), there are other ways of finding out the installed version, but not when installing it manually.

Therefore, I think it'd be a good idea to add a __version__ string to sigpy.

I don't know much about python packaging, but it could probably live in a file and just be read into, for example, setup.py. This would also make sure that that version is always accurate.

Best regards,
Christian

**Comment by frankong** [comment]
Good idea. 5193399bc726a3e4bed4d243ebe3065b27e39368 addresses this.
