### ISSUE TITLE
Issue with EspiritCalib for 3D data 

### ISSUE THREAD

**Issue by briannghiem** [mikgroup/sigpy#60]
**Describe the bug**
I am running into issues with computing the calibration matrix for a multicoil 3D image (ndim = 4). The array_to_blocks function only accepts inputs with ndim = {1, 2, 3}.

**To Reproduce**
1. Load multicoil 3D ksp data; I'm working with dimensions [ncoils, RO, PE1, PE2] = [12, 256, 218, 170]
2. Run mr.app.EspiritCalib(ksp).run()
3. Error raised: "Traceback (most recent call last):  
  File "<stdin>", line 1, in <module>  
  File "/cluster/home/brian.nghiem/.conda/envs/sigpy_env/lib/python3.7/site-packages/sigpy/mri/app.py", line 422, in __init__
    mat = sp.array_to_blocks(calib, kernel_shape, kernel_strides)   
  File "/cluster/home/brian.nghiem/.conda/envs/sigpy_env/lib/python3.7/site-packages/sigpy/block.py", line 103, in array_to_blocks  
    raise ValueError('Only support ndim=1, 2, or 3, got {}'.format(ndim))""

**Computer**
OS: Linux (remote cluster)

**Comment by frankong** [comment]
Thanks for letting me know. a05b481a6640cbad8d1e5d4e15b946bed10a95d1 fixes this.

**Comment by AlhaidariAziz** [comment]
Hi Dr. Ong, I'm wondering in case our ACS data are only centrally, volumetrically acquisitiioned (i.e. peripheral slices have no ASC date), Woud the commited changes (#a05b481) "using batch 3D array_to_block instead of 4D array_to_block in ESPIRiT" handle this. 

BR, 
Aziz,
