### ISSUE TITLE
Undersampling trajectories example 

### ISSUE THREAD

**Issue by gabrielziegler3** [mikgroup/sigpy#71]
Hi, I have been looking at the functions for undersampling described in the [docs page](https://sigpy.readthedocs.io/en/latest/_modules/sigpy/mri/samp.html), but I cannot see any example with them in the notebooks provided and the description for me is a bit confusing. Could anyone please post a demo on how to use these undersampling functions? 

I am trying to replicate compressed sensing experiments using radial and spiral trajectories for my bachelor thesis. 
Thank you

**Comment by sidward** [comment]
Hello,

As mentioned in the README, please email mrirecon@lists.eecs.berkeley.edu instead of posting an issue.

**Comment by frankong** [comment]
Closing issue with @zwep 's help
