### ISSUE TITLE
ESPIRiT with GPU producing different results compared to CPU

### ISSUE THREAD

**Issue by adithyaOvGu** [mikgroup/sigpy#73]
Hello, 

I have been using SigPy to perform L1-wavelet CS and TV reconstruction of undersampled data stored in h5 files. One of the steps in my workflow involves estimating Sensitivy maps of undersampled data with a certain ACS region using the ESPIRiT app. 

**My script produces the desired maps and reconstruction results while computing on a local system **with no GPU**. Because of the longer computation time, I deployed the same script in a remote machine with GPU**

The only changes made to the script was the addition of **device=sp.Device(0)** to the **ESPIRiT** app and convertion of cupy.ndarray to numpy.ndarray as seen in the lines below:

``` 
mps_msk = mr.app.EspiritCalib(Masked_ksp, calib_width=num_low_frequency, device=sp.Device(0)).run()
mps_msk = cupy.asnumpy(mps_msk) 
```

**Expected behavior**
Computation of Sensitivity maps (**in the local system**) for Undersampled data with ACS region = 13 produces the sensitivity maps and its coil combined image (slice number 6) as seen below. 
```
 mps_msk = mr.app.EspiritCalib(Masked_ksp, calib_width=num_low_frequency).run()
```
![Sense_13](https://user-images.githubusercontent.com/59664991/114709116-7b702100-9d2c-11eb-96c7-7b6a5fe6cd12.png)  ![Under_13_local](https://user-images.githubusercontent.com/59664991/114709125-7e6b1180-9d2c-11eb-9371-aee273698be3.png)

**Issue**
The ESPIRiT computation on the same data (with same ACS region) performed in the **remote machine with GPU**(device=sp.Device(0) enabled) lead to faster computation but produced **unexpected cropping** of the maps as seen in the below images.

![Sense_13_GPU](https://user-images.githubusercontent.com/59664991/114709795-4c0de400-9d2d-11eb-85b6-e94e9c70eb0b.png) ![Under_13_GPU](https://user-images.githubusercontent.com/59664991/114709809-4e703e00-9d2d-11eb-9b20-510eec38fc0e.png)

**Problem** 
This unexpected behavior of cropping in estimated maps leads to cropping or poor reconstruction of the Image as seen below. 

![L1W_13](https://user-images.githubusercontent.com/59664991/114711258-0a7e3880-9d2f-11eb-9a36-e73a4aad014e.png) ![L1W_13_GPU](https://user-images.githubusercontent.com/59664991/114711277-0eaa5600-9d2f-11eb-8ed3-d94f659561a4.png)

![TV_13](https://user-images.githubusercontent.com/59664991/114711350-1ff36280-9d2f-11eb-814c-6bb2e1dabb7d.png)
![TV_13_GPU](https://user-images.githubusercontent.com/59664991/114711359-2255bc80-9d2f-11eb-827f-cd5134d28155.png)

**Desktop (Local machine):**
- Machine: Macbook Pro mid 2012
 - OS: macOS Catalina
 - Version: 10.15.7
 - Graphics: Intel HD Graphics 4000 1536 MB
 - Memory: 8 GB 1600 MHz DDR3
 - Processor: 2,5 GHz Dual-Core Intel Core i5

**Desktop (Remote server):**
 - OS: Manjaro Linux 64bit / Linux 5.10.2-2-MANJARO
 - Graphics: GeForce RTX 2080 Ti 10GB

**Additional context**
After estimating the sensitivity maps, I convert cupy.ndarray to numpy.ndarray to store the data in the h5 file. As far as my understanding goes, this does not cause any changes in the data. 

**My input k-space shape to the Espirit app is [coils, RO, PE] and calib_width=num_low_frequency = 13 for 8-fold accelerated data.** 

I kindly request you to provide some insight and solution to this issue, so that I could make my work reproducible. 

PS: I would also like to thank all the developers and contributors of SigPy for providing us with this awesome toolkit.

**Comment by sidward** [comment]
At first glance, it could be related to numerical precision. Try reducing the crop value and see if the results are comparable then.

**Comment by adithyaOvGu** [comment]
> At first glance, it could be related to numerical precision. Try reducing the crop value and see if the results are comparable then.



> At first glance, it could be related to numerical precision. Try reducing the crop value and see if the results are comparable then.

I am currently not providing any specific crop values, but let me try introducing crop values and get back to you. Meanwhile, could you please elaborate on how on this "numerical precision"?

**Comment by sidward** [comment]
The default crop is 0.95. The API reference is here: [https://sigpy.readthedocs.io/en/latest/generated/sigpy.mri.app.EspiritCalib.html#sigpy.mri.app.EspiritCalib].

As for numerical precision, just from experience, processing on the CPU versus the GPU can sometimes have different numerical noise. In ESPIRiT, the crop variable is a threshold applied to a particular set of eigenvalues. For your case, my guess is that the eigenvalues are very close to 0.95 and on the GPU, some of them fall below 0.95 which causes the field of view to be smaller. An easy way to test this is to reduce the crop value to, say, 0.9.

**Comment by adithyaOvGu** [comment]
> The default crop is 0.95. The API reference is here: [https://sigpy.readthedocs.io/en/latest/generated/sigpy.mri.app.EspiritCalib.html#sigpy.mri.app.EspiritCalib].
> 
> As for numerical precision, just from experience, processing on the CPU versus the GPU can sometimes have different numerical noise. In ESPIRiT, the crop variable is a threshold applied to a particular set of eigenvalues. For your case, my guess is that the eigenvalues are very close to 0.95 and on the GPU, some of them fall below 0.95 which causes the field of view to be smaller. An easy way to test this is to reduce the crop value to, say, 0.9.

Thank you very much for this clarification. I tried specifying the crop value as 0.90, 0.85, 0.80 and for crop = 0.90 It resolved the issue with the sensitivity maps **most** of the undersampled data. This **problem still exists for certain data**

Example: 
![AXFLAIR_202_TV_90_0001](https://user-images.githubusercontent.com/59664991/115280224-fb8cf100-a147-11eb-949f-b783b259a4e5.png)  ![AXFLAIR_206_TV_90_0001](https://user-images.githubusercontent.com/59664991/115280235-ffb90e80-a147-11eb-8ca7-2e386a0f8de5.png)

![AXT1_201_TV_90_0001](https://user-images.githubusercontent.com/59664991/115280267-0ba4d080-a148-11eb-9f2c-c9d6b5c6d5ba.png) ![AXT1PRE_200_TV_90_0001](https://user-images.githubusercontent.com/59664991/115280519-50c90280-a148-11eb-8814-0e0d8cdb7611.png) ![AXT1POST_201_TV_90_0001](https://user-images.githubusercontent.com/59664991/115280603-69391d00-a148-11eb-9f49-3f5f7a5cc790.png)

The problem still exists to some extent for certain data, so I believe it could be a data-specific Issue. I will check if adjusting the Kernel_width parameter helps with completely eliminating this issue with sens maps (regardless of the acquisition & data?)

Do you also think adjusting Kernel_width could have some part in resolving the issues??

**Comment by sidward** [comment]
Yup, in general, a larger kernel width and smaller crop will be less likely to cut into the signal.

**Comment by adithyaOvGu** [comment]
> Yup, in general, a larger kernel width and smaller crop will be less likely to cut into the signal.

@sidward, Thanks a lot for the support and for answering my questions. I have 150 files, each containing k-space data of different acquisitions [AXFLAIR, AXT1, AXT1POST, AXT1PRE, AXT2]. Choosing the default crop & kernel_width was producing the unexpected maps for some data while working fine for the other when ESPIRiT was run on GPU. 

**By trial and error, A crop of 0.70 and kernel_width of 5 in ESPIRiT generated the expected sensitivity maps for all the data** (irrespective of acquisition type).

![AXFLAIR_202_TV_70_0001](https://user-images.githubusercontent.com/59664991/115781777-26cb4680-a3bb-11eb-92b4-44c968005aed.png)![AXFLAIR_206_TV_5_70_0001](https://user-images.githubusercontent.com/59664991/115781812-3054ae80-a3bb-11eb-8f55-2ab32470209d.png)
![AXT1_201_TV_70_0001](https://user-images.githubusercontent.com/59664991/115781842-39458000-a3bb-11eb-8646-1612fcd15642.png)![AXT1PRE_200_TV_70_0001](https://user-images.githubusercontent.com/59664991/115781869-42365180-a3bb-11eb-80f3-3e6b477d3dc0.png)
![AXT1POST_201_TV_80_0001](https://user-images.githubusercontent.com/59664991/115781878-45c9d880-a3bb-11eb-91fa-acea0fc35950.png)

**Could you please suggest to me some reading material or literature that could help me understand how crop value & kernel width affects the computation of sensitivity maps in ESPIRiT?** 

Do we consider this issue closed or ?

**Comment by sidward** [comment]
I'm glad it helps! With respect to literature, I would recommend the original paper:

> https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.24751

I previously worked on a project to automatically estimate ESPIRiT parameters. If that is of interest to you, please see the following:

> https://onlinelibrary-wiley-com.libproxy.mit.edu/doi/full/10.1002/mrm.28386

Finally for the issue itself, I think it should be closed as there is a parameter combination that works for all cases.

**Comment by adithyaOvGu** [comment]
> I'm glad it helps! With respect to literature, I would recommend the original paper:
> 
> > https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.24751
> 
> I previously worked on a project to automatically estimate ESPIRiT parameters. If that is of interest to you, please see the following:
> 
> > https://onlinelibrary-wiley-com.libproxy.mit.edu/doi/full/10.1002/mrm.28386
> 
> Finally for the issue itself, I think it should be closed as there is a parameter combination that works for all cases.

Thanks a lot for the literature & the project link, will definitely look into it. 

Marking this issue as closed.
