### ISSUE TITLE
Cupy failed import should not be a exception, but a warning

### ISSUE THREAD

**Issue by ad12** [mikgroup/sigpy#77]
**Is your feature request related to a problem? Please describe.**
CuPy is a useful library for GPU-based ndarray operations; however there can often be issues with installation. SigPy has been useful in making the CuPy dependency optional; however, in the current state, the dependency is not really optional.

In the case where the `cupy` library is installed (`pip/conda install`) but not properly configured (e.g. wrong nvcc version is active), the importing `cupy` fails as shown below. Currently, sigpy attempts to set `cupy_enabled` by checking `util.find_spec("cupy") is not None`. However, this is not sufficient, as the cupy package can still be installed but can fail on import.

```python
>>> import cupy
Traceback (most recent call last):
  File "/home/usr/miniconda3/envs/dl_ss_env/lib/python3.7/site-packages/cupy/__init__.py", line 16, in <module>
    from cupy import _core  # NOQA
  File "/home/usr/miniconda3/envs/dl_ss_env/lib/python3.7/site-packages/cupy/_core/__init__.py", line 1, in <module>
    from cupy._core import core  # NOQA
ImportError: libcublas.so.10: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usr/miniconda3/envs/dl_ss_env/lib/python3.7/site-packages/cupy/__init__.py", line 37, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: libcublas.so.10: cannot open shared object file: No such file or directory
```

**Describe the solution you'd like**
Even if `import cupy` fails when `cupy` is installed, sigpy should not fail. Currently, sigpy passes along the ImportError raised by cupy, which causes sigpy to error out.

Because cupy is an optional dependency, sigpy should catch the exception, print a warning message to the user, and continue on with `cupy_enabled=False`. I believe the code below should do the trick:

```python
# in sigpy.config
from importlib import util
import warnings

cupy_enabled = util.find_spec("cupy") is not None
if cupy_enabled:
    try:
        import cupy
    except ImportError as e:
        warnings.warn(e)
        cupy_enabled=False
if cupy_enabled:  # pragma: no cover
    cudnn_enabled = util.find_spec("cupy.cuda.cudnn") is not None
    nccl_enabled = util.find_spec("cupy.cuda.nccl") is not None
else:
    cudnn_enabled = False
    nccl_enabled = False
```

**Comment by sidward** [comment]
I've struggled with pip :sweat_smile:  Cupy has always worked for anaconda out of the box for me

**Comment by ad12** [comment]
yea haha - conda does a great job in simplifying the install. But in the case it is installed with pip, something like this could help?

Out of curiosity, does the conda install of cupy work on machines without gpus? I'm guessing we would run into similar issues in that case

**Comment by frankong** [comment]
@ad12 What you said makes sense. Can you do a pull request with a fix similar to the one you show above? Thanks
