### ISSUE TITLE
Installation issue on python 3.8.5

### ISSUE THREAD

**Issue by hkaggarwal** [mikgroup/sigpy#84]
Hello,

I have Anaconda python 3.8.
For installation, I gave the command
$conda install -c frankong sigpy

But it gives the following error:
_________________________________________________________________
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - sigpy -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
________________________________________________________

I can try downgrading my python to 3.7 but is it possible to upgrade sigpy to work with python 3.8.

Thanks,
Hemant

**Comment by frankong** [comment]
Thanks for letting me know. I've updated the conda build to sweep through Python versions from 3.6 to 3.9 (350ab6a9f916050f73fca9af711722f87e3fda43). If you run the usual conda install command, it should work:
`conda install -c frankong sigpy`
