### ISSUE TITLE
Unexpected behavior of `coil_batch_size` parameter on `sigpy.mri.app`

### ISSUE THREAD

**Issue by mscipio** [mikgroup/sigpy#99]
**Describe the bug**
'sigpy.mri.app.TotalVariationRecon` and `sigpy.mri.app.SenseRecon` behave differently if parameter `coil_batch_size` is smaller than the total number of coils

**Expected behavior**
The final reconstructed image should be the same, no matter the coil batch size used. The doc itself states that that parameter affects only performance

**Screenshots**
RECONSTRUCTED IMAGE WITH `coil_batch_size < 20` (with 20 = # coils)
![image](https://user-images.githubusercontent.com/17526160/136060208-e713144a-0143-49dd-8296-0dac2c65f986.png)

RECONSTRUCTED IMAGE WITH `coil_batch_size = 20` (with 20 = # coils)
![image](https://user-images.githubusercontent.com/17526160/136060301-22ccabea-d15c-4d2d-b0f6-2f37502f4415.png)

**Additional context**
Maybe the `coil_batch_size` parameter operates on a different dimension than axis=0?
These are the shapes of the arrays I am trying to pass to either apps:
![image](https://user-images.githubusercontent.com/17526160/136060528-bc8ca5ae-9548-4710-a562-a5165acf5533.png)

**Comment by sidward** [comment]
Hi! Could you please check if you're using a version that includes pull request #93?

**Comment by mscipio** [comment]
> Hi! Could you please check if you're using a version that includes pull request #93?

Hi! I am not sure how I can check that. I believe I am using the version available on pip.
Has that pull request been merged with the stable version that comes with pip?

**Comment by sidward** [comment]
@frankong  If you think it is reasonable, could you please update the project on PyPI?

@mscipio Until the above is sorted, it might be easier to install via git clone. After cloning, please look the "[Installation for Developers](https://github.com/mikgroup/sigpy#installation-for-developers)" in the README.

**Comment by mscipio** [comment]
yes, this is what I just did, and it worked.

If you decide to update the version on PyPI, make sure to check the version number, as right now, even though the version here on GitHub is different from the one on PyPI, the version number is still the same.

Thank you!

**Comment by sidward** [comment]
Sounds good! I will leave it to @frankong to decide on whether to update the version number/ PyPI repo. I am closing this request for now, but please feel free to post again if there's anything I can help with.
